### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by mlozynskyy** [mlozynskyy/node-rest-api-skeleton#1]
- [ ] Add circleCI or github CI
- [ ] Docker and docker compose
- [ ] Configure unit and functional tests and add them to CI
- [ ] Readme and docs
- [ ] Configure class validator
- [ ] TypeORM configuration
